# Generated by Django 4.2 on 2023-05-10 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHub', '0003_image_views_alter_image_date_alter_image_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(default=datetime.time(6, 19, 38, 844049)),
        ),
    ]
