# Generated by Django 4.2 on 2023-05-10 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHub', '0004_alter_image_date_alter_image_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(default=datetime.time(6, 20, 58, 665816)),
        ),
    ]
