# Generated by Django 4.2 on 2023-05-10 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHub', '0005_alter_image_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(default=datetime.time(6, 49, 26, 990818)),
        ),
    ]
