# Generated by Django 4.2 on 2023-05-10 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHub', '0007_alter_image_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(default=datetime.time(7, 18, 41, 95390)),
        ),
    ]
