# Generated by Django 4.2 on 2023-05-10 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHub', '0008_alter_image_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(default=datetime.time(7, 22, 16, 247193)),
        ),
    ]
