# Generated by Django 4.2 on 2023-05-10 11:59

import ImageHub.models
import ImageHub.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHub', '0009_alter_image_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=ImageHub.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), ImageHub.validators.MinFileSizeValidator(10240, message='File size should be at least 10kb'), ImageHub.validators.MaxFileSizeValidator(10485760, message='File size should not exceed 10mb.')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\w\\s]{2,}$', message='Only alphanumeric values are allowed.')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(default=datetime.time(11, 58, 15, 565503)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[a-zA-Z]', message='Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[a-zA-Z]', message='Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]{5,15}$', message='1.At least one alphabet\n 2.At least one numeric value\n 3.Allowed size 5 to 15 character')]),
        ),
    ]
