# Generated by Django 4.2 on 2023-05-10 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHub', '0010_user_master_key_alter_image_image_alter_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(default=datetime.time(11, 59, 14, 452711)),
        ),
        migrations.AlterField(
            model_name='user',
            name='master_key',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
