# Generated by Django 4.2 on 2023-05-12 06:57

import ImageHub.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageHub', '0011_alter_image_time_alter_user_master_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 12)),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=ImageHub.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^(?=.*[A-Za-z]{3})[A-Za-z0-9]{3,30}$', message='Only alphanumeric values are allowed.')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.TimeField(default=datetime.time(6, 57, 38, 273801)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[a-zA-Z]+$', message='Only alphabets are allowed to set Name.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[a-zA-Z]+$', message='Only alphabets are allowed to set Name.')]),
        ),
    ]
